name: Build LKM for KernelSU
on:
  workflow_call:
  workflow_dispatch:
jobs:
  build-lkm:
    strategy:
      matrix:
        kmi:
          - android12-5.10
          - android13-5.10
          - android13-5.15
          - android14-5.15
          - android14-6.1
          - android15-6.6
          - android16-6.12
          - android17-6.18
    uses: ./.github/workflows/ddk-lkm.yml
    with:
      kmi: ${{ matrix.kmi }}
      expected_size2: "775"
      expected_hash2: "5fab9586f7ec077701103949ecb4c24819e3f9e5648e9d5b54600069fa9292b7"
